### ISSUE TITLE
Implement shed_lint.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#107]
Lint a shed repository instead of just tools. This is a meta-issue to track 4 issues open by @peterjc.
- [ ] Check sample files #96.
- [x] Check for a README #89.
- [x] Check rst in any `.rst` files #91.
- [x] Lint `tool_dependencies.xml`.
- [x] ~Cross reference `tool_dependencies.xml` with tools #90.~
- [x] Lint `.shed.yml`
- [x] Lint `repository_dependencies.xml`.
- [x] Check that packages belong only to the category `Tool Dependency Packages`. 8c2a45a14605e9695575ad1ce80d0791ba571d3d
- [x] Check tool dependency actions that are difficult to verify with XSD. 8117e038917f9c2914e7871d519e1af448cec54b
- [x] Check for required type based on repository type. #156
- [x] ~Check for changeset and tool shed attributes in `tool_dependencies.xml` files. (https://github.com/galaxyproject/tools-iuc/pull/149#issuecomment-104311715)~

**Comment by erasche** [comment]
How would you feel about checking for .shed.yml? The, admittedly, under debate, current example is: https://gist.github.com/erasche/25a2405f259f9d2fb14f

**Comment by jmchilton** [comment]
Some initial work here https://github.com/galaxyproject/planemo/pull/130 addressing linting ``tool_dependencies.xml``, ``repository_dependencies.xml`` and ``.shed.yml`` but not the rest of this - but there is at least a spot for it now.

**Comment by peterjc** [comment]
@erasche did you mean finding a ``.shed.yml`` means the folder is a Tool Shed repository? Or when checking a folder thought to be a Tool Shed repository, it ought to have a ``.shed.yml``? This is important for recursion - how should ``planemo shed_list -r ...`` decide what to look at?

**Comment by erasche** [comment]
@peterjc nmo, I meant checking that a `.shed.yml` file was present in what looks like a tool folder/maybe validating the contents of it. See #130 and "Bare minimum to lint .shed.yml files."

**Comment by peterjc** [comment]
Thanks for the clarification @erasche - basic linting of ``.shed.yml`` is happening now (ticked on the TODO list here), but I agree that can probably be more through.

See also #156 for dependency packages.

**Comment by erasche** [comment]
#96 would've caught https://github.com/galaxyproject/tools-iuc/issues/148

**Comment by erasche** [comment]
```
planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error tools/jq
Linting repository /home/hxr/work/tools-iuc/tools/jq
+Linting tool /home/hxr/work/tools-iuc/tools/jq/jq.xml
Applying linter citations... WARNING
.. WARNING: No citations found, consider adding citations to your tool.
Applying linter shed_metadata... WARNING
.. WARNING: Missing shed metadata field [description] for repository
.. WARNING: Missing shed metadata field [long_description] for repository
.. WARNING: Missing shed metadata field [remote_repository_url] for repository
.. WARNING: Missing shed metadata field [homepage_url] for repository
.. WARNING: Missing shed metadata field [categories] for repository
```

I think a missing .shed.yml file should be an error. Some of the metadata fields like homepage_url are nice-to-haves and thus are fine being warnings, but a missing .shed.yml is a problem, and we missed it during the JQ merge. Someone (i.e. myself, whenever I find five seconds amongst packing for my move) should PR this change.

**Comment by jmchilton** [comment]
Sample files are the last unchecked thing and there is an open Galaxy PR for that.
