### ISSUE TITLE
CWL Support

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#270]
Make planemo a premier CLI toolkit for CWL development.

 - [x] Allow serving cwl tools in Galaxy (``serve --cwl``) #337.
 - [x] Add ``cwl_script`` command to convert CWL tools and jobs to bash scripts. #355 
 - [x] Add ``run`` command to run CWL tools and jobs through Galaxy. #336 #340 #454
 - [X] Add ``run --engine cwltool`` command to run CWL tools via reference implementation.
 - [x] Use reference implementation validation to ``lint`` CWL tools via validation.
 - [ ] Add ``cwl_convert`` command to convert a Galaxy tool into a CWL tool.
 - [ ] Extend ``serve`` to allow serving CWL workflows as well as tools.
 - [ ] ``planemo cottentail`` https://github.com/rabix/cottontail | https://github.com/ekalinin/nodeenv/blob/master/nodeenv.py

Update (10/28/15): Topic came up at GCC and BOSC so I have sketched more a grand plan here now.

**Comment by mr-c** [comment]
@jmchilton looks like boxes 2 and 3 can be checked

**Comment by jmchilton** [comment]
Sure thing - I forgot about this issue thanks. cwl_script needs some love and the planemo of cwl_run also needs enhancements I think.

**Comment by jmchilton** [comment]
Closing this issue - serving CWL workflows will now just work once Galaxy supports CWL workflows since serving CWL tools and serving Galaxy workflows works. The ``cwl_convert`` issue already exists (https://github.com/galaxyproject/planemo/issues/315) and I just created an issue for cottentail support (https://github.com/galaxyproject/planemo/issues/485).

**Comment by jmchilton** [comment]
Open CWL issues can be tracked using the CWL tag - https://github.com/galaxyproject/planemo/issues?q=is%3Aissue+is%3Aopen+label%3Acwl
