### ISSUE TITLE
Planemo 2016 Abstract

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/planemo#408]
Conference season abstracts are due soon (GCC and ISMB/BOSC). I (@jmchilton) would like to follow up last year's talk "Planemo – A Galaxy Tool SDK" with a talk "Planemo – A Scientific Workflow SDK" suitable for both BOSC and GCC.

Talk Outline:
- [ ] Overview of Recent Galaxy Workflow Enhancements:
  - [ ] Implicit connections.
    - [X] ~~Backend https://github.com/galaxyproject/galaxy/commit/e0a5e82bdae407535b9d7c98e3dcf851b63d01a0~~
    - [ ] UI (TODO)
    - [ ] Slide
  - [ ] Nested Workflows.
    - [X] ~~First pass in 16.01. https://github.com/galaxyproject/galaxy/pull/1306~~
    - [ ] Follow up - allow "upgrading" workflows.
    - [ ] Slides
  - [ ] Labels on all the things.
    - [x] ~~Implementation https://github.com/galaxyproject/galaxy/pull/1306~~
    - [ ] Slide
  - [ ] Collection Operations and Patterns.
    - [ ] Implementation (Issue https://github.com/galaxyproject/galaxy/issues/1644, Failed PR https://github.com/galaxyproject/galaxy/pull/1313) New PR (https://github.com/galaxyproject/galaxy/pull/2434)
    - [ ] Slides
  - [ ] UI enhancements.
    - [ ] Slide
- [ ] Format 2 Galaxy Workflows - A writable specification for native Galaxy workflows.
  - [x] Implement population of default tool state (TODO: create Galaxy issue and PR)
  - [X] Better handling of conditionals (https://github.com/galaxyproject/galaxy/pull/1777)
  - [ ] Describe format, give examples.
    - [ ] Slides
  - [X] Implement a library on top of bioblend. https://github.com/jmchilton/gxformat2
  - [ ] Usage.
    - [ ] Serving Workflows
      - [X] Profiles for workflow development. #445.
      - [X] Serve for Galaxy workflows (`planemo serve <workflow>`). https://github.com/galaxyproject/planemo/pull/454
      - [x] Enhanced profiles for Galaxy. https://github.com/galaxyproject/planemo/issues/447.
      - [ ] Slides
    - [ ] Running Workflows (`planemo run <workflow> <job>`)
      - [x] Initial engine implementation https://github.com/galaxyproject/planemo/pull/454
      - [x] Refine engine for workflows
      - [ ] Slides
    - [ ] Testing Workflows (`planemo test <workflow>`)
      - [ ] Pull Galaxy test stuff out into galaxy-lib for reuse here.
      - [x] Refine engine for testing.
      - [ ] Slides
- [ ] ~~The State of the CWL (skip at BOSC)~~ (@mr-c submitted an abstract - will cover this).
  - [ ] ~~Slides (Michael and Peter will probably have something to use there).~~
- [x] Building and Testing CWL Tools with Planemo
  - [X] Build and lint. (https://github.com/galaxyproject/planemo/pull/466)
  - [x] Test with cwltool.
  - [x] Test with Galaxy.
  - [x] Serve in Galaxy.
- [ ] Building and Testing CWL Workflows with Planemo
  - [ ] Lint and test with cwltool.
  - [ ] Future plans - Galaxy support.
- [ ] Planemo Machine - An Environment for Galaxy and CWL workflow development.

Too Stretched Goals:
- [ ] Workflows from file paths like tools (https://github.com/galaxyproject/galaxy/issues/1740)

Remaining dev priorities:
- [ ] Emphemaris and shed picture for gxformat2 workflows!
- [ ] Implement `--slurm`.
